; PlatformIO project configuration
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

board_build.filesystem = littlefs
; see docs/architektur.md (partition scheme)
board_build.partitions = partitions_custom.csv

lib_deps =
    https://github.com/pschatzmann/ESP32-A2DP.git
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/pschatzmann/arduino-libhelix.git
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ESP32Async/AsyncTCP.git
    bblanchon/ArduinoJson @ ^7

build_flags =
    -DCORE_DEBUG_LEVEL=1
